[build]
  command = "yarn build"
  functions = "out_functions"
  publish = "out"

[build.environment]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
